
package ventasdao.ui.abm;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ventasdao.controladores.CategoriaControlador;
import ventasdao.controladores.ClienteControlador;
import ventasdao.controladores.FacturaControlador;
import ventasdao.controladores.LineaFacturaControlador;
import ventasdao.controladores.ProductoControlador;
import ventasdao.objetos.Categoria;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.Factura;
import ventasdao.objetos.LineaFactura;
import ventasdao.objetos.Producto;
import ventasdao.objetos.ProductoCantidad;
import ventasdao.ui.grilla.GrillaCliente;
import ventasdao.ui.grilla.GrillaFactura;
import ventasdao.ui.grilla.GrillaProducto;

/**
 *
 * @author Administrador
 */
public class AbmFactura extends javax.swing.JInternalFrame {
    
    private ProductoControlador productoControlador;
    private CategoriaControlador categoriaControlador;
    private GrillaProducto grillaProducto;
    private DefaultComboBoxModel modelCombo;
    private DefaultComboBoxModel modelComboProductos;
    private FacturaControlador  facturaControlador;
    private LineaFacturaControlador lineaFacturaControlador;
    private ArrayList<Cliente> clientes;
    
    GrillaFactura grillaFactura;
    
    public AbmFactura() {
        initComponents();
        
        facturaControlador  = new  FacturaControlador();
        lineaFacturaControlador = new LineaFacturaControlador();
        ClienteControlador ClienteControlador = new ClienteControlador();
        ClienteControlador = new ClienteControlador();
        
        productoControlador = new ProductoControlador();
        
        try {
            grillaFactura = new GrillaFactura(new ArrayList<LineaFactura>());
            jtFactura.setModel(grillaFactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            clientes = ClienteControlador.listar();
            ArrayList<Producto> productos = productoControlador.listar();
            
            modelCombo = new DefaultComboBoxModel(clientes.toArray());
            jCbCliente.setModel(modelCombo);
            
            modelComboProductos = new DefaultComboBoxModel(productos.toArray());
            jCBProducto.setModel(modelComboProductos);
            
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCliente = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jCbCliente = new javax.swing.JComboBox<>();
        jLProducto = new javax.swing.JLabel();
        jCBProducto = new javax.swing.JComboBox<>();
        jLPrecio = new javax.swing.JLabel();
        jLCantidad = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jtfCantidad = new javax.swing.JTextField();
        jBTEliminar = new javax.swing.JButton();
        jBTAGregar = new javax.swing.JButton();
        jLCantidad1 = new javax.swing.JLabel();
        jtfSubtotal = new javax.swing.JTextField();
        jLfecha = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLObservaciones = new javax.swing.JLabel();
        jtfObservaciones = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jlbTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLCliente.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCliente.setText("Cliente");

        jLTitulo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTitulo.setText("Factura");

        jCbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbClienteActionPerformed(evt);
            }
        });

        jLProducto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLProducto.setText("Producto");

        jCBProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBProductoItemStateChanged(evt);
            }
        });
        jCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProductoActionPerformed(evt);
            }
        });

        jLPrecio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLPrecio.setText("Precio");

        jLCantidad.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCantidad.setText("Cantidad");

        jtfPrecio.setEnabled(false);

        jtfCantidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtfCantidadPropertyChange(evt);
            }
        });
        jtfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCantidadKeyReleased(evt);
            }
        });

        jBTEliminar.setText("Eliminar");

        jBTAGregar.setText("Agregar");
        jBTAGregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAGregarActionPerformed(evt);
            }
        });

        jLCantidad1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLCantidad1.setText("SubTotal");

        jtfSubtotal.setEnabled(false);

        jLfecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLfecha.setText("Fecha");

        jLObservaciones.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLObservaciones.setText("Observaciones");

        jtfObservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfObservacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCliente)
                            .addComponent(jLProducto)
                            .addComponent(jLPrecio))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(jLfecha)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jLCantidad1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLCantidad)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLObservaciones)
                        .addGap(18, 18, 18)
                        .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBTAGregar)
                        .addGap(52, 52, 52)
                        .addComponent(jBTEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLTitulo)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCliente))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLProducto)
                            .addComponent(jCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLfecha)))
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPrecio)
                    .addComponent(jLCantidad)
                    .addComponent(jtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCantidad1)
                    .addComponent(jtfSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLObservaciones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTAGregar)
                    .addComponent(jBTEliminar))
                .addGap(21, 21, 21))
        );

        jLTotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLTotal.setText("Total");

        jtFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 2, 2)));
        jtFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Productos", "Precio Unitario", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtFactura);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("TOTAL");

        jlbTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbTotal.setText("$0.00");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(591, 591, 591)
                        .addComponent(jLTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jlbTotal))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlbTotal))
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1263, 1263, 1263)
                .addComponent(jLTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbClienteActionPerformed

    private void jCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBProductoActionPerformed

    private void jCBProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBProductoItemStateChanged
        // TODO add your handling code here:
        //selection Change
        
        Producto producto = (Producto)jCBProducto.getSelectedItem();
        try{
            Producto pr =  productoControlador.extraer(producto.getId());
            
            jtfPrecio.setText(""+pr.getPrecio());
            
        }catch(SQLException ex){
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jCBProductoItemStateChanged

    private void jtfCantidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtfCantidadPropertyChange
        // TODO add your handling code here:
        //quantity change

        
        
    }//GEN-LAST:event_jtfCantidadPropertyChange

    private void jtfCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadKeyReleased
        // TODO add your handling code here:
        
        
        try{
            
            Double cantidad =  Double.parseDouble(jtfCantidad.getText());
            Double precio =  Double.parseDouble(jtfPrecio.getText());
            
            Double subTotal = cantidad * precio;
            
            jtfSubtotal.setText(""+ subTotal);
            
        }catch(Exception ex){
            
            jtfSubtotal.setText("");
            
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jtfCantidadKeyReleased

    private void jBTAGregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAGregarActionPerformed
        // TODO add your handling code here:
        //agregar 
        
        LineaFactura lineaFactura = new LineaFactura();
        
        Producto producto = (Producto)jCBProducto.getSelectedItem();
        
        lineaFactura.setId(producto.getId());
        lineaFactura.setProducto(producto);

        
        Double cantidad = 0d;
        Double importe = 0d;
        try{
            cantidad = Double.parseDouble(jtfCantidad.getText());
            
            importe = cantidad * lineaFactura.getProducto().getPrecio();
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        lineaFactura.setCantidad(cantidad);
        lineaFactura.setImporte(importe);
        
        
        grillaFactura.agregar(lineaFactura);
        jtFactura.updateUI();
        
        jlbTotal.setText("$" + grillaFactura.total);
        
    }//GEN-LAST:event_jBTAGregarActionPerformed
//Guardar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Factura factura = new Factura();
        
        factura.setDate(jdcFecha.getDate());
        factura.setObservacion(jtfObservaciones.getText());
        factura.setCliente((Cliente)jCbCliente.getSelectedItem());
        factura.setTotal(grillaFactura.total);
        
        try { 
            
           int FacturaId = facturaControlador.crearyRetornarId(factura);
           factura.setId(FacturaId);
           
           for(LineaFactura lineaFactura:grillaFactura.getProductos()){
               lineaFactura.setFactura(factura);
               lineaFacturaControlador.crear(lineaFactura);
           }
           javax.swing.JOptionPane.showMessageDialog(this, "¡La Factura se guardo con Exito!", "Exito", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfObservacionesActionPerformed
    
    
    private void refreshTable(){
        try {
           // jtFactura.setModel(new GrillaCliente(ClienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAGregar;
    private javax.swing.JButton jBTEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBProducto;
    private javax.swing.JComboBox<String> jCbCliente;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCantidad1;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLObservaciones;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLProducto;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JTable jtFactura;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfObservaciones;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfSubtotal;
    // End of variables declaration//GEN-END:variables

   // private void limpiarCampos() {
    //   jtfDescripcion.setText("");
     //  jtfNombre.setText("");
     //  jtfPrecio.setText("");
   // }
}
